name: Generate trophy

on:
  schedule:
    - cron: "0 0 * * *"  # รันทุกวันเที่ยงคืน
  workflow_dispatch:       # กดรันเองได้จากแท็บ Actions

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: chitcha-aaa
          output_path: profile/trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add profile/trophy.svg
          git commit -m "Update trophy" || exit 0
          git push
